CREATE TABLE password_reset_token (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id bigint      NOT NULL,
    token_hash    varchar(64) NOT NULL,
    expires_at    timestamptz NOT NULL,
    used_at       timestamptz,
    created_at    timestamptz NOT NULL,
    CONSTRAINT fk_password_reset_token_credential
        FOREIGN KEY (credential_id) REFERENCES user_credential (id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash)
);

-- token_hash는 SHA-256 hex 64자다. 토큰이 랜덤 32바이트라 전수 대입이 불가능해
-- 인증번호(6자리, BCrypt)와 달리 느린 해시가 필요 없다.
