CREATE TABLE verification_code (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number  varchar(11) NOT NULL,
    code_hash     varchar(72) NOT NULL,
    purpose       varchar(20) NOT NULL,
    expires_at    timestamptz NOT NULL,
    used_at       timestamptz,
    attempt_count int         NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL
);

-- users를 참조하지 않는다. 아직 가입하지 않은 번호로도 코드를 발급하기 때문이다.
