CREATE TABLE region (
    id        bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      varchar(10)      NOT NULL,
    sido      varchar(20)      NOT NULL,
    sigungu   varchar(20)      NOT NULL,
    dong      varchar(20)      NOT NULL,
    latitude  double precision NOT NULL,
    longitude double precision NOT NULL,
    CONSTRAINT uk_region_code UNIQUE (code)
);
