CREATE TABLE user_region (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL,
    region_id  bigint      NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT fk_user_region_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_user_region_region FOREIGN KEY (region_id) REFERENCES region (id),
    CONSTRAINT uk_user_region_user_id_region_id UNIQUE (user_id, region_id)
);

-- "사용자당 최대 2개"는 여기에 없다. DB 제약으로 표현하려면 트리거가 필요해 과하다.
-- 애플리케이션 서비스에서 검증한다 (spec/domain.md).
