CREATE TABLE product (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   bigint        NOT NULL,
    region_id   bigint        NOT NULL,
    title       varchar(100)  NOT NULL,
    description varchar(2000) NOT NULL,
    price       int           NOT NULL,
    category    varchar(20)   NOT NULL,
    status      varchar(20)   NOT NULL DEFAULT 'ON_SALE',
    created_at  timestamptz   NOT NULL,
    updated_at  timestamptz   NOT NULL,
    deleted_at  timestamptz,
    CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES users (id),
    CONSTRAINT fk_product_region FOREIGN KEY (region_id) REFERENCES region (id)
);

-- idx_product_list는 일부러 만들지 않는다.
-- mock 20만 건에서 인덱스 없이 목록 조회를 먼저 측정한 뒤 생성해 재측정한다 (spec/erd.md).
-- 이것이 M2 성능 실험의 주인공이다.

CREATE TABLE product_image (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint       NOT NULL,
    url        varchar(500) NOT NULL,
    sort_order int          NOT NULL,
    CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT uk_product_image_sort_order UNIQUE (product_id, sort_order)
);
