CREATE TABLE user_credential (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint      NOT NULL,
    provider       varchar(20) NOT NULL,
    provider_id    varchar(255),
    email          varchar(255),
    email_verified boolean     NOT NULL DEFAULT false,
    password_hash  varchar(72),
    created_at     timestamptz NOT NULL,
    CONSTRAINT fk_user_credential_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_user_credential_provider_id UNIQUE (provider, provider_id)
);

-- LOCAL 인증수단끼리만 이메일이 유일하다. 소셜에서 받아온 이메일은 중복을 허용한다.
CREATE UNIQUE INDEX uk_user_credential_local_email
    ON user_credential (provider, email) WHERE provider = 'LOCAL';
