CREATE TABLE users (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname     varchar(20) NOT NULL,
    phone_number varchar(11) NOT NULL,
    created_at   timestamptz NOT NULL,
    deleted_at   timestamptz
);

-- 살아있는 사용자끼리만 유일하다. 탈퇴한 사용자의 닉네임·번호는 재사용 가능하다.
-- WHERE 절이 붙는 유니크는 테이블 제약으로 표현할 수 없어 인덱스로 만든다.
CREATE UNIQUE INDEX uk_user_nickname
    ON users (nickname) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_user_phone_number
    ON users (phone_number) WHERE deleted_at IS NULL;
